### ISSUE TITLE
Using session throws pyasn1.type.error.ValueConstraintError

### ISSUE THREAD

**Issue by mfrlin** [vincentbernat/snimpy#30]
Hello I am trying to use your library instead of pysnmp.

pysnmp example:

    cmdGen = cmdgen.CommandGenerator()
    errorIndication, errorStatus, errorIndex, varBindTable = cmdGen.nextCmd(
        cmdgen.CommunityData(config.COMMUNITY),
        cmdgen.UdpTransportTarget((config.HOST, config.PORT)),
        config.OID,
        lexicographicMode=False,
        ignoreNonIncreasingOid=True,
        lookupValue=False, lookupNames=False
    )
    for varBindTableRow in varBindTable:
        for name, val in varBindTableRow:
            print('%s' % (val,))

snimpy example:

    s = Session(config.HOST+':'+str(config.PORT), community=config.COMMUNITY, version=2)
    res = s.walk('.'+config.OID)
    print res

pysnmp yields:
230
0
0
49
10

while snimpy throws an error
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/martin/.virtualenvs/snmp/lib/python2.7/site-packages/memory_profiler.py", line 853, in <module>
    execfile(__file__, ns, ns)
  File "test3.py", line 17, in <module>
    test()
  File "/home/martin/.virtualenvs/snmp/lib/python2.7/site-packages/memory_profiler.py", line 445, in f
    result = func(*args, **kwds)
  File "test3.py", line 10, in test
    res = s.walk('.'+config.OID)
  File "/home/martin/.virtualenvs/snmp/local/lib/python2.7/site-packages/snimpy/snmp.py", line 272, in walk
    return self._op(self._cmdgen.bulkCmd, *args)
  File "/home/martin/.virtualenvs/snmp/local/lib/python2.7/site-packages/snimpy/snmp.py", line 226, in _op
    self._auth, self._transport, *oids)
  File "/home/martin/.virtualenvs/snmp/local/lib/python2.7/site-packages/pysnmp/entity/rfc3413/oneliner/cmdgen.py", line 630, in bulkCmd
    contextEngineId, contextName
  File "/home/martin/.virtualenvs/snmp/local/lib/python2.7/site-packages/pysnmp/entity/rfc3413/oneliner/cmdgen.py", line 380, in bulkCmd
    authData, transportTarget
  File "/home/martin/.virtualenvs/snmp/local/lib/python2.7/site-packages/pysnmp/entity/rfc3413/oneliner/cmdgen.py", line 55, in cfgCmdGen
    authData.securityName
  File "/home/martin/.virtualenvs/snmp/local/lib/python2.7/site-packages/pysnmp/entity/config.py", line 59, in addV1System
    snmpEngine, communityIndex
  File "/home/martin/.virtualenvs/snmp/local/lib/python2.7/site-packages/pysnmp/entity/config.py", line 52, in __cookV1SystemInfo
    tblIdx = snmpCommunityEntry.getInstIdFromIndices(communityIndex)
  File "/home/martin/.virtualenvs/snmp/lib/python2.7/site-packages/pysnmp/smi/mibs/SNMPv2-SMI.py", line 1096, in getInstIdFromIndices
    mibObj.syntax.clone(indices[idx]), impliedFlag
  File "/home/martin/.virtualenvs/snmp/local/lib/python2.7/site-packages/pyasn1/type/univ.py", line 300, in clone
    value, tagSet, subtypeSpec, encoding, binValue, hexValue
  File "/home/martin/.virtualenvs/snmp/local/lib/python2.7/site-packages/pyasn1/type/univ.py", line 284, in __init__
    base.AbstractSimpleAsn1Item.__init__(self, value, tagSet, subtypeSpec)
  File "/home/martin/.virtualenvs/snmp/local/lib/python2.7/site-packages/pyasn1/type/base.py", line 69, in __init__
    self._verifySubtypeSpec(value)
  File "/home/martin/.virtualenvs/snmp/local/lib/python2.7/site-packages/pyasn1/type/base.py", line 33, in _verifySubtypeSpec
    raise c('%s at %s' % (i, self.__class__.__name__))
pyasn1.type.error.ValueConstraintError: ConstraintsIntersection(ConstraintsIntersection(ConstraintsIntersection(ConstraintsIntersection(), ValueSizeConstraint(0, 65535)), ValueSizeConstraint(0, 255)), ValueSizeConstraint(1, 32)) failed at: "ValueSizeConstraint(1, 32) failed at: "1.3.6.1.4.1.318.1.3.2.17_APC_AP9630"" at SnmpAdminString
```

Am I using it wrong? This section is not really documented and I am a beginner regarding snmp.

**Comment by vincentbernat** [comment]
`Session.walk()` expects a tuple, not a string.

Also note that snimpy is meant to be used only through the manager. All the other details are implementation details that may change. If you don't use MIB, snimpy is not the best match since its target is really to leverage MIB to get a "pythonic" interface to SNMP.

**Comment by vincentbernat** [comment]
Not really a bug, unless I am mistaken.
