### ISSUE TITLE
RuntimeError due to Dictionary Size change when Cache is enabled

### ISSUE THREAD

**Issue by hanynowsky** [vincentbernat/snimpy#34]
- STACKTRACE
==============
```
[2015-06-11 16:04:16,276: WARNING/Worker-3] Traceback (most recent call last):
  File "/home/masac/masac/masac/seed/tasks.py", line 382, in send_router_metrics
    metrics[m.ifDescr[index]]['ifHCOutOctets'] = m.ifHCOutOctets[index]
  File "/home/masac/.virtualenvs/masac-dj1.8-py3.4/lib/python3.4/site-packages/snimpy/manager.py", line 365, in __getitem__
    return self._op("get", index)
  File "/home/masac/.virtualenvs/masac-dj1.8-py3.4/lib/python3.4/site-packages/snimpy/manager.py", line 352, in _op
    *args)
  File "/home/masac/.virtualenvs/masac-dj1.8-py3.4/lib/python3.4/site-packages/snimpy/manager.py", line 122, in get
    return self.getorwalk("get", *args)
  File "/home/masac/.virtualenvs/masac-dj1.8-py3.4/lib/python3.4/site-packages/snimpy/manager.py", line 118, in getorwalk
    self.flush()
  File "/home/masac/.virtualenvs/masac-dj1.8-py3.4/lib/python3.4/site-packages/snimpy/manager.py", line 132, in flush
    for k in keys:
RuntimeError: dictionary changed size during iteration


```
- If you put a condition while looping on m.ifDescr, while cache is enabled, you get the above error.
```python
metrics = {}
                        try:
                                m = M(host=ip, retries=0, community=comm, version=2, timeout=SWITCH_TIMEOUT, cache=1)
                        except:
                                print(traceback.format_exc())
                        try:
                                for index in m.ifDescr:
                                        try:
                                                if "thernet" in str(m.ifDescr[index]) and "unrouted" not in str(m.ifDescr[index]) and "Vlan" not in str(m.ifDescr[index]) and "Null" not in str(m.ifDescr[index]):
                                                        metrics[m.ifDescr[index]] = {}
                                                        metrics[m.ifDescr[index]]['ifHCOutOctets'] = m.ifHCOutOctets[index]
                                                        metrics[m.ifDescr[index]]['ifHCInOctets'] = m.ifHCInOctets[index]
                                                        # print(index, repr(m.ifDescr[index]), repr(m.ifHCOutOctets[index]), repr(m.ifHCInOctets[index]))
                                        except SNMPNoSuchInstance:
                                                if LOG_DEBUG == True:
                                                        print("SNMPNoSuchInstance for " + hostname + " " + ip + " " + comm)
                                                continue
                        except gaierror as ge:
                                # print(traceback.format_exc())
                                print("gaierror for " + hostname + " " + ip + " " + comm)
                                if LOG_DEBUG == True:
                                        print("Snimpy Manager Exception: gaierror")
### Remainder of code.....
```

**Comment by vincentbernat** [comment]
I have pushed a fix for that in 4cdd8b05ac2c. You should be able to apply it manually to test.

**Comment by vincentbernat** [comment]
By the way, I am quite happy that you are using Python 3. This has been some effort to port Snimpy to it and it is a delight that there are some real users. :)

**Comment by hanynowsky** [comment]
Thanks for your great work. It's A great Module. Yes we started to adopt Py3 for new projects. I am quite glad too.
