### ISSUE TITLE
SNMP get on sysObjectID ends with AttributeError: prettyOut

### ISSUE THREAD

**Issue by cbueche** [vincentbernat/snimpy#47]
### works on snimpy 0.8.1

```python
m2 = M(host='test2.domain', community='comm')
m2.sysObjectID
````

returns the expected value:

    <Oid: 1.3.6.1.4.1.9.1.1208>

### broken on snimpy 0.8.8

```python
m2 = M(host='test2.domain', community='comm')
m2.sysObjectID
```

fails with:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/myself/.pyenv/versions/venv266/lib/python2.6/site-packages/snimpy/manager.py", line 298, in __getattribute__
    oid, result = self._session.get(a.oid + (0,))[0]
  File "/Users/myself/.pyenv/versions/venv266/lib/python2.6/site-packages/snimpy/snmp.py", line 271, in get
    :return: a list of tuples with the retrieved OID and the raw value.
  File "/Users/myself/.pyenv/versions/venv266/lib/python2.6/site-packages/snimpy/snmp.py", line 263, in _op
    # This seems to be filtered
  File "/Users/myself/.pyenv/versions/venv266/lib/python2.6/site-packages/snimpy/snmp.py", line 221, in _convert
    rfc1902.OctetString: bytes,
  File "/Users/myself/.pyenv/versions/venv266/lib/python2.6/site-packages/pysnmp/smi/rfc1902.py", line 573, in __getattr__
    raise AttributeError(attr)
AttributeError: prettyOut
```

## sudo tcpdump port 161

```
16:07:07.709666 IP 10.251.5.163.58394 > test2.domain.snmp:  C=comm GetRequest(28)  system.sysObjectID.0
16:07:07.712976 IP test2.domain.snmp > 10.251.5.163.58394:  C=comm GetResponse(37)  system.sysObjectID.0=E:cisco.1.1317
```

I guess something is not correct, but I do not really understand why the sysOid value get's interpreted as rfc1902.IpAddress in _convert().

I can easily run test code if desired.

**Comment by vincentbernat** [comment]
Thanks for the report. I think this should be easy to fix. I'll try later today.

**Comment by vincentbernat** [comment]
I am unable to reproduce here. Could you give the output of snmpget? I don't know what the `E:` means in tcpdump.

**Comment by cbueche** [comment]
Here a pair of snmpget:

````
snmpwalk -v 2c -c comm device SNMPv2-MIB::sysObjectID.0
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.9.1.1208
```
```
snmpwalk -On -v 2c -c comm device SNMPv2-MIB::sysObjectID.0
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.9.1.1208
```

I think the "E:" means "enterprises".

**Comment by vincentbernat** [comment]
OK, I am able to reproduce this bug on Travis: https://travis-ci.org/vincentbernat/snimpy/jobs/102670039
