### ISSUE TITLE
Doc example fails: snimpy.mib.SMIException: unable to find b'IF-MIB' (check the path)

### ISSUE THREAD

**Issue by edouard-lopez** [vincentbernat/snimpy#57]
I followed [the doc](https://snimpy.readthedocs.io/en/latest/usage.html#regular-python-module) but got the following error:

```
>>> from snimpy.manager import Manager as M
from snimpy.manager import load

load("IF-MIB")
m = M("localhost")
print(m.ifDescr[0])
Traceback (most recent call last):
  File "<input>", line 4, in <module>
  File "/home/ed8/projects/coaxis-opt/env/lib/python3.5/site-packages/snimpy/manager.py", line 578, in load
    m = mib.load(mibname)
  File "/home/ed8/projects/coaxis-opt/env/lib/python3.5/site-packages/snimpy/mib.py", line 605, in load
    raise SMIException("unable to find {0} (check the path)".format(mib))
snimpy.mib.SMIException: unable to find b'IF-MIB' (check the path)
```

What is `IF-MIB`? Do I need to install some package on my system?

**Comment by vincentbernat** [comment]
If you are on Ubuntu, you need to `apt-get install snmp-mibs-downloader`.
