### ISSUE TITLE
Doc example fails: Doc example fails: 

### ISSUE THREAD

**Issue by edouard-lopez** [vincentbernat/snimpy#60]
I followed [the doc](https://snimpy.readthedocs.io/en/latest/usage.html#regular-python-module) but got the following error:

```
from snimpy.manager import Manager as M
from snimpy.manager import load

load("IF-MIB")
m = M("localhost")
print(m.ifDescr[0])
Traceback (most recent call last):
  File "<input>", line 6, in <module>
  File "/home/ed8/projects/coaxis-opt/env/lib/python3.5/site-packages/snimpy/manager.py", line 537, in __getitem__
    return self._op("get", self._oid_suffix + index)
  File "/home/ed8/projects/coaxis-opt/env/lib/python3.5/site-packages/snimpy/manager.py", line 403, in _op
    *args)
  File "/home/ed8/projects/coaxis-opt/env/lib/python3.5/site-packages/snimpy/snmp.py", line 286, in get
    return self._op(self._cmdgen.getCmd, *oids)
  File "/home/ed8/projects/coaxis-opt/env/lib/python3.5/site-packages/snimpy/snmp.py", line 258, in _op
    raise SNMPException(str(errorIndication))
snimpy.snmp.SNMPException: No SNMP response received before timeout
```

I tried with another device I can ping and telnet to with same result

### Question

Do I need to install a client/agent on my machine to be able to run snmp?

**Comment by vincentbernat** [comment]
If `IF-MIB` is present on your system, locate it and use the full path in `load()`. Otherwise, configure `/etc/smi.conf` to let Snimpy discover it automatically.

**Comment by edouard-lopez** [comment]
@vincentbernat I updated my question as I did some mess and didn't copy/paste the right content.

From what I gathered I need to install 

    apt-get install snmp snmpd
