### ISSUE TITLE
Attribute missing

### ISSUE THREAD

**Issue by BusbyActual** [vincentbernat/snimpy#71]
Running snimpy on OSX and trying to get list of OIDS from mib files. I'm going through the examples in the docs to test it out and I'm getting this error in every format. I've tried through the console, as a script, and a python module.  

### mib.py

#!/usr/bin/env snimpy

load("RS-COMMON-MIB.mib")
m = M("localhost")
print(m.ifDescr[0])

### Error
```

Traceback (most recent call last):
  File "/usr/local/bin/snimpy", line 11, in <module>
    sys.exit(interact())
  File "/usr/local/lib/python2.7/site-packages/snimpy/main.py", line 70, in interact
    exec(compile(open(argv[0]).read(), argv[0], 'exec')) in local
  File "mib.py", line 5, in <module>
    print(m.ifDescr[0])
  File "/usr/local/lib/python2.7/site-packages/snimpy/manager.py", line 316, in __getattribute__
    m, a = self._locate(attribute)
  File "/usr/local/lib/python2.7/site-packages/snimpy/manager.py", line 311, in _locate
    raise AttributeError("{0} is not an attribute".format(attribute))
AttributeError: ifDescr is not an attribute

```

**Comment by vincentbernat** [comment]
You also need to `load("IF-MIB")`.

**Comment by BusbyActual** [comment]
That helped. Now i'm getting SyntaxError: EOL while scanning string literal. I think it's referring to my mib file it doesn't have '\n' anywhere in the mib. Here is an excerpt: 

xyBroadcastThing OBJECT-IDENTITY
        STATUS current
        DESCRIPTION
            "Sub-tree for broadcast things."
        ::= { xyBroadcast 4 }


Does it need to be formatted differently?

**Comment by vincentbernat** [comment]
The problem is more likely in your Python script, like if you forgot to close a quote.

**Comment by BusbyActual** [comment]
It was an issue of mismatched quotes. Now I'm getting a timeout error. If I remove the print function it works fine. I'm trying to list the Oids and names of the Oids after loading the MIB files into memory. I see the majority of the methods to access Oids are internal and shouldn't be accessed directly.  How would one go about accessing them or is that not intended? Thanks again for all your help.

```
#!/usr/bin/env snimpy

load("IF-MIB")
load("/users/admin/desktop/mib/mibfiles/RS-COMMON-MIB.mib")
m = M("localhost")
print(m.ifDescr[0])

```

###Console
```
Traceback (most recent call last):
  File "/usr/local/bin/snimpy", line 11, in <module>
    sys.exit(interact())
  File "/usr/local/lib/python2.7/site-packages/snimpy/main.py", line 70, in interact
    exec(compile(open(argv[0]).read(), argv[0], 'exec')) in local
  File "mib.py", line 6, in <module>
    print(m.ifDescr[0])
  File "/usr/local/lib/python2.7/site-packages/snimpy/manager.py", line 537, in __getitem__
    return self._op("get", self._oid_suffix + index)
  File "/usr/local/lib/python2.7/site-packages/snimpy/manager.py", line 403, in _op
    *args)
  File "/usr/local/lib/python2.7/site-packages/snimpy/snmp.py", line 286, in get
    return self._op(self._cmdgen.getCmd, *oids)
  File "/usr/local/lib/python2.7/site-packages/snimpy/snmp.py", line 258, in _op
    raise SNMPException(str(errorIndication))
snimpy.snmp.SNMPException: No SNMP response received before timeout
```

**Comment by vincentbernat** [comment]
It means either you don't have a SNMP server running on localhost or the community is not "public".
